### ISSUE TITLE
pulseaudio 4 on Ubuntu 14.04

### ISSUE THREAD

**Issue by randallsquared** [graysky2/pulseaudio-ctl#20]
So, I installed this today, and the first use muted my default sink.

I'm writing this mainly for anyone using the same versions I am, and wondering what to do to get their audio back.  I don't expect that it would be worth patching pulseaudio-ctl to fix this, and I don't have a machine with other versions to test on in any case.   

### Step 1:  

     $ pacmd list-sinks|grep '* index'
     * index: 1   # yours might differ, I guess?  Anyway, use the same number below before " false"
     $ pacmd
     Welcome to PulseAudio! Use "help" for usage information.
     >>> set-sink-mute 1 false

You should have audio now.  Press Ctrl+d to exit pacmd.

### Step 2: 

If this worked for you, then fixing pulseaudio-ctl is simple.

First make sure that the problem I had is really the problem you had:

     $ grep 'volume: front' /usr/bin/pulseaudio-ctl

You should have five lines of output that contain "... CURVOL ...".  If so:

     $ sudo sed -i -e 's/volume: front/volume: 0/g' /usr/bin/pulseaudio-ctl

**Comment by randallsquared** [comment]
This does work, but reporting on the curvol is broken due to it not checking again for PA version every time.  I'll send a pull request shortly for that fix.

**Comment by graysky2** [comment]
Thanks merged.
