### ISSUE TITLE
BARCHART does not acknowledge UPPER_THRESHOLD

### ISSUE THREAD

**Issue by mixedCase** [graysky2/pulseaudio-ctl#33]
When UPPER_THRESHOLD is set to a level higher than 100, the bar reported still relies con $CURVOL instead of recalculating the new percentage.

This is I believe the expected behavior, as can be seen on something like KMixer.

**Comment by bebehei** [comment]
:+1: I experience this problem, too!

**Comment by mixedCase** [comment]
I sent a PR in #34 that fixes the problem but the author seems to be MIA, feel free to clone that if you want it fixed.

**Comment by graysky2** [comment]
Not MIA... just fell off the radar.  Will review and comment or merge shortly.

**Comment by graysky2** [comment]
Merged.https://github.com/graysky2/pulseaudio-ctl/commit/c7b092efc82f95cd132d9b6236be9c7f5d6a7800
