### ISSUE TITLE
Feature Request: Instructions for compiling and installing that even we Ubuntards can understand

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [graysky2/pulseaudio-ctl#40]
Title says it all. I'd love to try this but I can't derive any meaning from a sentence like
"Setup the via a make." With all respect and appreciation, I diffidently point out, that's not English. Can anybody point me to clear instructions?

**Comment by graysky2** [comment]
```
make
sudo make install
```

**Comment by Lew-Rockwell-Fan** [comment]
That was quick. Thank you. Seems to work. Only cli volume control I've seen that does. I thought maybe it was myth. :-)

**Comment by graysky2** [comment]
No myth.  For your own safety, you should learn how to read Makefiles before blindly installing software.  Enjoy.
