### ISSUE TITLE
Config loading does not respect $PREFIX

### ISSUE THREAD

**Issue by TLATER** [graysky2/pulseaudio-ctl#47]
When installed using the likes of `PREFIX=/usr/local make install` pulseaudio-ctl still attempts to load configuration from `usr/share/pulseaudio-ctl/config.skel`, resulting in a broken installation.

**Comment by graysky2** [comment]
Works for me:
```
% make DESTDIR=tit PREFIX=/usr/local install
% tree tit                                                                                      :(
tit
└── usr
    └── local
        ├── bin
        │   └── pulseaudio-ctl
        └── share
            ├── man
            │   └── man1
            │       └── pulseaudio-ctl.1.gz
            ├── pulseaudio-ctl
            │   └── config.skel
            └── zsh
                └── site-functions
                    └── _pulseaudio-ctl
```

**Comment by TLATER** [comment]
The issue is not the directory structure; it does install to the correct location.

However, pulseaudio-ctl will fail to run because it will attempt to load the config from `/usr/share/pulseaudio-ctl/config.skel`, when its actual location is in `/usr/local/share/pulseaudio-ctl/config.skel`.

**Comment by graysky2** [comment]
I understand now... will fix shortly.

**Comment by graysky2** [comment]
Actually, it works as expected for me:
```
% grep local ./tit/usr/local/bin/pulseaudio-ctl
SKEL="/usr/local/share/pulseaudio-ctl/config.skel"
```

**Comment by TLATER** [comment]
Hm, sorry, I can confirm this is actually working. My bad, I must have made a mistake somehow - though I have no idea how the files ended up in the correct location anyway.

Either way, thanks for the quick resolution - I'll leave closing this to you :)
