### ISSUE TITLE
`Invalid volume specification`

### ISSUE THREAD

**Issue by paulbdavis** [graysky2/pulseaudio-ctl#48]
Getting this when trying to run volume commands like `pulseaudio-ctl up`

On Arch Linux, with`pulseaudio` and `libpulse` version `11.0+6+g01f489c3`

**Comment by graysky2** [comment]
I'm showing `11.0+6+g01f489c3-1` is the current release.  Did you build from git?

**Comment by paulbdavis** [comment]
Yes, that's correct, I just left off the `pkgrel` for some reason..

**Comment by graysky2** [comment]
I see what they did.... try v1.65.

**Comment by paulbdavis** [comment]
Seems to still be failing on arch, 

```
 % pactl --version | grep pactl | sed 's/^pactl //'
11.0-6-g01f48
```

```
 % echo "$(pactl --version | grep pactl | sed 's/^pactl //') > 10.9" | bc
0
```

^ seems like without processing off the non numeric parts of the version number, it does not get flagged as the new version

```
pactl --version | grep pactl | sed -e 's/^pactl //' -e 's/\([0-9.]\+\).*/\1/'
```

^ this addition to the sed command does the trick for me

**Comment by graysky2** [comment]
Odd... it worked for me on 11.0-6-g01f48.  You're right about a more robust stanza though.

**Comment by paulbdavis** [comment]
There was just another release of the libpulse package on arch and it is all working again. Seems like the arch maintainers are releasing got snapshots of pulse for some reason. On Sep 19, 2017 1:17 PM, graysky <notifications@github.com> wrote:Odd... it worked for me on 11.0-6-g01f48.  You're right about a more robust stanza though.
