### ISSUE TITLE
get current volume level

### ISSUE THREAD

**Issue by lopippo** [graysky2/pulseaudio-ctl#62]
Greetings,

my use case is to play an alert sound from a cron entry. For that I want to set the output level at its maximum, so that the sound may be heared from another room. But once the sound has been played, I want to set the level back to its prior level.

Would it be possible to have a function to retrieve the current sound level value so that it can be stored for later use in a script ?

Thank you so much for this nice program.

**Comment by graysky2** [comment]
Suggest you write a script that sets the vol to max, does your work, the resets it to you previous level.  This is outside the scope of this util.

**Comment by lopippo** [comment]
Your answer got me thinking: does not the existing script have already that code...

This is the get current volume functionality I was asking for:

case "$1" in
  G|g)
    # get current volume and print it as a percentage
    refreshcurvol
    printf "$CURVOL\n"
    ;;

So that in a script I can do this:

current_volume=$(pulseaudio-ctl) G
do my stuff
pulseaudio-ctl set $current_volume

Anyway... thanks for this script.
